# Generated by Django 4.0 on 2022-07-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='creation_time',
            field=models.DateTimeField(default='2022-07-23 23:44'),
        ),
        migrations.AlterField(
            model_name='media',
            name='datetime',
            field=models.DateTimeField(default='2022-07-23 23:44'),
        ),
        migrations.AlterField(
            model_name='order',
            name='datetime',
            field=models.DateTimeField(default='2022-07-23 23:44'),
        ),
        migrations.AlterField(
            model_name='question',
            name='creation_time',
            field=models.DateTimeField(default='2022-07-23 23:44'),
        ),
        migrations.AlterField(
            model_name='review',
            name='creation_time',
            field=models.DateTimeField(default='2022-07-23 23:44'),
        ),
    ]
